language: python
python:
  - "3.8"

install:
  - pip install .
  - pip install codecov
  - pip install coverage

script:
  - coverage run -m pytest

after_success:
  - codecov

deploy:
  provider: pypi
  user: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  distributions: "sdist bdist_wheel bdist_msi --target-version 3.8"
  on:
    tags: true

notifications:
  email: false
