language: python
python:
  - "3.8"

install:
  - pip install .

script:
  - coverage run -m pytest

deploy:
  provider: pypi
  user: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    tags: true

notifications:
  email: false
